name: Sync to Hugging Face Space

on:
  push:
    branches: [ main, master ] # Run automatically when you push to main/master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all history

      - name: Push to Hugging Face
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          # REPLACE the line below with your actual Hugging Face username and Space name
          huggingface_repo_id: pratuldeshpande/Quantum_maps_backend
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          subdirectory: 'backend'
